/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/home/core/components/BreadcrumbsLink': RouteRecordInfo<'/home/core/components/BreadcrumbsLink', '/home/core/components/BreadcrumbsLink', Record<never, never>, Record<never, never>>,
    '/home/core/components/ShowCategory': RouteRecordInfo<'/home/core/components/ShowCategory', '/home/core/components/ShowCategory', Record<never, never>, Record<never, never>>,
    '/home/core/components/TreeViewCheckbox': RouteRecordInfo<'/home/core/components/TreeViewCheckbox', '/home/core/components/TreeViewCheckbox', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/login/core/components/LeftSectionLogin': RouteRecordInfo<'/login/core/components/LeftSectionLogin', '/login/core/components/LeftSectionLogin', Record<never, never>, Record<never, never>>,
    '/login/core/components/RightSectionLogin': RouteRecordInfo<'/login/core/components/RightSectionLogin', '/login/core/components/RightSectionLogin', Record<never, never>, Record<never, never>>,
  }
}
